### ISSUE TITLE
CPAN::Audit

### ISSUE THREAD

**Issue by briandfoy** [perladvent/Perl-Advent#146]
Which Perl module do you want to write about: CPAN::Audit

Please give a short description of the article you want to write. Two to three sentences is fine:

I recently took over CPAN::Audit, which trawls through your modules and matches them up to known vulnerabilities. I'd like to include an article that merely makes people aware of the tool, how they can contribute, and so on.

**Comment by oalders** [comment]
Thank you so much for committing to provide an article to the Perl Advent calendar. It's a tradition that so many of us look forward to and we're happy you've volunteered your time to help us make 2022's calendar a success. Now, the initial submission deadline for an initial draft was Nov 1, 2022, but it's not too late to participate. We want help you to get your article merged. In order to avoid having the Advent Calendar team work furiously through the Holiday season in a rush to complete the calendar, we're asking you to submit your post by Dec 1, which is one week from today.

If we haven't heard from you by Dec 1st we will sadly need to close this issue and continue on without your article. We hope very much to make it to the magical number of 25 articles, but in order to accomplish this we need everyone who has offered to write an article to provide it. Please help us to make 2022 a year with a full calendar of fun, interesting and quirky Advent articles.

**Comment by oalders** [comment]
Article is at #233

**Comment by thibaultduponchelle** [comment]
day 19

**Comment by oalders** [comment]
Thanks @briandfoy!
