### ISSUE TITLE
Find out the time your script to execute

### ISSUE THREAD

**Issue by manwar** [perladvent/Perl-Advent#147]
Which Perl module do you want to write about:
App::Timer
Please give a short description of the article you want to write. Two to three sentences is fine:
I always want to know how much time my script took to run. I have many App::* distributions where I put the code to calculate the total time spent. At this point, I decided to come up with a generic solution that can be applied to all without having to write a single line code to get the result. In the App::Timer, I try propose the solution.
It would be nice, if I get to share this with the rest of the Perl community through Perl Advent Calendar.

**Comment by briandfoy** [comment]
There's now a script to start your article for you and show off the pod enhancements you can use:

    perl script/new_article

Good luck!

**Comment by thibaultduponchelle** [comment]
@manwar If you still feel ready, could be the right time 🕦 for an App::Timer article 😄

**Comment by oalders** [comment]
Thank you so much for committing to provide an article to the Perl Advent calendar. It's a tradition that so many of us look forward to and we're happy you've volunteered your time to help us make 2022's calendar a success. Now, the initial submission deadline for an initial draft was Nov 1, 2022, but it's not too late to participate. We want help you to get your article merged. In order to avoid having the Advent Calendar team work furiously through the Holiday season in a rush to complete the calendar, we're asking you to submit your post by Dec 1, which is one week from today.

If we haven't heard from you by Dec 1st we will sadly need to close this issue and continue on without your article. We hope very much to make it to the magical number of 25 articles, but in order to accomplish this we need everyone who has offered to write an article to provide it. Please help us to make 2022 a year with a full calendar of fun, interesting and quirky Advent articles.

**Comment by oalders** [comment]
Thanks for all of your support via the Perl Weekly @manwar. That was incredibly helpful. I see the article was posted on your own blog site, so I'll go ahead and close this issue. I hope you had a good holiday season.
