### ISSUE TITLE
Article on the new features of Data::Printer 1.x

### ISSUE THREAD

**Issue by garu** [perladvent/Perl-Advent#164]
Which Perl module do you want to write about:

Data::Printer

Please give a short description of the article you want to write. Two to three sentences is fine:

Data::Printer has evolved a lot since its initial release 11 years ago. It now offers multiple filters out of the box, reference counters, memory size, color themes, profiles, even a config file you can use to setup things on a per-module basis so you can toggle and adjust your debug output without ever touching your codebase.

I may be biased, but I believe it's a very useful tool and ~more people~ Santa should be aware of it :)

**Comment by thibaultduponchelle** [comment]
You're not biased 😄  Data::Printer is great 💯

**Comment by oalders** [comment]
Thank you so much for committing to provide an article to the Perl Advent calendar. It's a tradition that so many of us look forward to and we're happy you've volunteered your time to help us make 2022's calendar a success. Now, the initial submission deadline for an initial draft was Nov 1, 2022, but it's not too late to participate. We want help you to get your article merged. In order to avoid having the Advent Calendar team work furiously through the Holiday season in a rush to complete the calendar, we're asking you to submit your post by Dec 1, which is one week from today.

If we haven't heard from you by Dec 1st we will sadly need to close this issue and continue on without your article. We hope very much to make it to the magical number of 25 articles, but in order to accomplish this we need everyone who has offered to write an article to provide it. Please help us to make 2022 a year with a full calendar of fun, interesting and quirky Advent articles.

**Comment by garu** [comment]
sorry, I was not aware of that deadline. I'll post the article later
tonight.

thanks!

**Comment by garu** [comment]
Sorry, my kid is sick, I'm going to need just one or two more days. I'm confident I'll make the deadline of dec 1st.

**Comment by garu** [comment]
Final draft submitted as PR #225, ready for scrutiny. I'll upload the images tomorrow.

Thanks!

**Comment by thibaultduponchelle** [comment]
day 23

**Comment by oalders** [comment]
Thanks @garu! I hope your little one is feeling better.

**Comment by thibaultduponchelle** [comment]
Day 22
