### ISSUE TITLE
relocatable perl

### ISSUE THREAD

**Issue by skaji** [perladvent/Perl-Advent#187]
### Which Perl module do you want to write about:

https://github.com/skaji/relocatable-perl

This is not a module actually:)

### Please give a short description of the article you want to write. Two to three sentences is fine:

Some programming languages provide their pre-built binaries. For example, nodejs 
https://nodejs.org/en/download/ and golang https://go.dev/dl/

What if perl also provides its pre-built binaries?
Is it useful? I think it is!

**Comment by thibaultduponchelle** [comment]
:+1:

I see you already contributed in the past but if you want there's a script you can use to get started. See https://github.com/perladvent/Perl-Advent/issues/147#issuecomment-1200134125

**Comment by oalders** [comment]
I didn't even know about this project. I look forward to reading about it. 😄

**Comment by oalders** [comment]
Thank you so much for committing to provide an article to the Perl Advent calendar. It's a tradition that so many of us look forward to and we're happy you've volunteered your time to help us make 2022's calendar a success. Now, the initial submission deadline for an initial draft was Nov 1, 2022, but it's not too late to participate. We want help you to get your article merged. In order to avoid having the Advent Calendar team work furiously through the Holiday season in a rush to complete the calendar, we're asking you to submit your post by Dec 1, which is one week from today.

If we haven't heard from you by Dec 1st we will sadly need to close this issue and continue on without your article. We hope very much to make it to the magical number of 25 articles, but in order to accomplish this we need everyone who has offered to write an article to provide it. Please help us to make 2022 a year with a full calendar of fun, interesting and quirky Advent articles.

**Comment by thibaultduponchelle** [comment]
Probably day 16
