### ISSUE TITLE
New article idea: Net::CIDR::Lite

### ISSUE THREAD

**Issue by openstrike** [perladvent/Perl-Advent#192]
Which Perl module do you want to write about:

[Net::CIDR::Lite](https://metacpan.org/pod/Net::CIDR::Lite)

Please give a short description of the article you want to write. Two to three sentences is fine:

This module allows construction of lists of CIDR-specified netblocks for matching against. The article would use the scenario of known naughty/nice networks and permit matching against those to determine if the inbound letters to Santa warrant gifts based on their source address.

**Comment by oalders** [comment]
Thank you so much for committing to provide an article to the Perl Advent calendar. It's a tradition that so many of us look forward to and we're happy you've volunteered your time to help us make 2022's calendar a success. Now, the initial submission deadline for an initial draft was Nov 1, 2022, but it's not too late to participate. We want help you to get your article merged. In order to avoid having the Advent Calendar team work furiously through the Holiday season in a rush to complete the calendar, we're asking you to submit your post by Dec 1, which is one week from today.

If we haven't heard from you by Dec 1st we will sadly need to close this issue and continue on without your article. We hope very much to make it to the magical number of 25 articles, but in order to accomplish this we need everyone who has offered to write an article to provide it. Please help us to make 2022 a year with a full calendar of fun, interesting and quirky Advent articles.

**Comment by openstrike** [comment]
Just in case it wasn't obvious, the first draft is in PR #220

**Comment by openstrike** [comment]
Closing this now since the article has been merged. Thanks.

**Comment by thibaultduponchelle** [comment]
day 17
