### ISSUE TITLE
Binding to Kotlin using FFI::Platypus

### ISSUE THREAD

**Issue by jjatria** [perladvent/Perl-Advent#365]
**Which Perl module do you want to write about:**

FFI::Platypus and FFI::C

**Please give a short description of the article you want to write. Two to three sentences is fine:**

I recently had to write something that would bind with a library written in Kotlin. When doing this, [Kotlin wraps the exported functions in a structure](https://kotlinlang.org/docs/native-dynamic-libraries.html#use-generated-headers-from-c) that needs to be navigated around, which made figuring this out tricky at the start. If we are still short on articles, I figure this would be a useful pattern to have lying around somewhere.

**Comment by openstrike** [comment]
It does sound useful - thanks.

There have been a couple of FFI::Platypus articles in previous years:

- [With OpenGL](https://perladvent.org/2015/2015-12-03.html)
- [With Go](https://perladvent.org/2019/2019-12-04.html)

but from what you have written it sounds like this is more about the wrangling with the Kotlin interface than about Platypus itself so that would be good to have.

**Comment by oalders** [comment]
@jjatria do you have an ETA for submitting the article?

**Comment by oalders** [comment]
Bump!

**Comment by jjatria** [comment]
@oalders I'm so sorry for the silence and the delay! I've been down with covid all this week, but I'm coming out of it now. I should be able to send in a submission this evening.

Thanks for the reminders! :bow:

**Comment by oalders** [comment]
I hope you feel better soon, @jjatria! If you can't get the submission in, we can figure something out. If you do have something to ship, that's great too! 🎄

**Comment by jjatria** [comment]
@oalders Pushed a draft to #398 :sweat_drops:

**Comment by oalders** [comment]
Close via #398

**Comment by oalders** [comment]
And, that's a wrap!
